#!/bin/bash
# Entry point to the program
#
# Author: Paul McPhillips
# Student: 40646715

# Check if the user is not root
if [ "$EUID" -ne 0 ]
	then
		echo -e "\e[31mThis must be run with elevated privileges\e[0m"
		exit
fi

# Display the user menu
source Scripts/Menu
