#!/bin/bash
# This script copies the
# files to each docker
# container
#
# Author: Paul McPhillips
# Student: 40646715

# Check is script is run as root or with sudo
if [ "$EUID" -ne 0 ]
then
	echo -e "\e[31mThis must be run as root\e[0m"
	exit
fi
echo ""
echo ""
while true
do
	# Display the working directory folders and request a selection
	echo "Where would you like to copy the files from?"
	echo -e "\e[1;36m"
	ls -R	
	echo -e "\e[0m"
	# Ask the user for the folder where the text files are then
	# ask which container the files should be copied to
	read -p "Select a directory where the text files are stored (Enter 0 to quit): " choice
	case $choice in
		0)
			source Scripts/Menu
			;;

		*)
			echo "Copying files to con1"
			for each in $choice/Docker1/*
			do
				sudo docker cp $each con1:/home/
			done
			echo "Copying files to con2"
			for each in $choice/Docker2/*
			do
				sudo docker cp $each con2:/home/
			done
			echo "Copying files to con3"
			for each in $choice/Docker3/*
			do
				sudo docker cp $each con3:/home/
			done
			echo "Finished copying files"
			source Scripts/Menu
			;;
	esac
done


