#!/bin/bash
#
# This script will create 3 containers
# with an Ubuntu image, named:
#
#	con1
#	con2
#	con3
#
# Author: Paul McPhillips
# Student: 40646715
if [ "$EUID" -ne 0 ]
then
	echo -e "\e[31mThis must be run as root\e[0m"
	exit
fi
echo ""
sleep 0.5
echo -n "Creating Containers"
sleep 0.5
echo ""
docker run -t -i -d --name con1 ubuntu /bin/bash
docker run -t -i -d --name con2 ubuntu /bin/bash
docker run -t -i -d --name con3 ubuntu /bin/bash

docker start con1
docker start con2
docker start con3
echo -ne "Containers Created"
docker ps
sleep 0.5
echo ""
sleep 1
source Scripts/Menu
